spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

user:
  password:
    length:
      min: 8
